### ISSUE TITLE
Drozer should be added in next release of Android Tamer 

### ISSUE THREAD

**Issue by bugwrangler** [anantshri/androidtamer#3]
V2 doesn’t have drozer inbuilt with android tamer 2

**Comment by anantshri** [comment]
Let me double check i suppose you will find the older version of drozer i.e. mercury in it. Back in the days when i released it mercury used to be the name.

**Comment by bugwrangler** [comment]
yeah probably, i didn't check for the mercury.

**Comment by anantshri** [comment]
Drozer is available along with https://github.com/AndroidTamer/drozer_checks in Tamer 4
