### ISSUE TITLE
Please add pidcat https://github.com/JakeWharton/pidcat

### ISSUE THREAD

**Issue by bugwrangler** [anantshri/androidtamer#4]

**Comment by anantshri** [comment]
noted and will be added in next release. 

Thanks for the contribution.

**Comment by bugwrangler** [comment]
:+1:

**Comment by anantshri** [comment]
pidcat 1.4.1 is by default available with debian using it right now but we might upgrade to using latest version in Tamer: issue tracked here : https://github.com/AndroidTamer/Tools_Repository/issues/68
